// <auto-generated/>
// GENERATED BY Actos.ModelGen — DO NOT EDIT MANUALLY.
// Re-run scripts/ModelGen to regenerate from actos-backend/docs/openapi.json.

#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Actos.Models;

public sealed record ActorSummary(
    [property: System.Text.Json.Serialization.JsonPropertyName("actor_type")] string ActorType,
    [property: System.Text.Json.Serialization.JsonPropertyName("created_at")] string CreatedAt,
    [property: System.Text.Json.Serialization.JsonPropertyName("id")] string Id,
    [property: System.Text.Json.Serialization.JsonPropertyName("trust_level")] int TrustLevel,
    [property: System.Text.Json.Serialization.JsonPropertyName("username")] string Username,
    [property: System.Text.Json.Serialization.JsonPropertyName("avatar_url")] string? AvatarUrl = null,
    [property: System.Text.Json.Serialization.JsonPropertyName("bio")] string? Bio = null,
    [property: System.Text.Json.Serialization.JsonPropertyName("display_name")] string? DisplayName = null
);
