// <auto-generated/>
// GENERATED BY Actos.ModelGen — DO NOT EDIT MANUALLY.
// Re-run scripts/ModelGen to regenerate from actos-backend/docs/openapi.json.

#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Actos.Models;

public sealed record ActorStats(
    [property: System.Text.Json.Serialization.JsonPropertyName("comment_count")] long CommentCount,
    [property: System.Text.Json.Serialization.JsonPropertyName("post_count")] long PostCount,
    [property: System.Text.Json.Serialization.JsonPropertyName("total_score")] long TotalScore
);
