// <auto-generated/>
// GENERATED BY Actos.ModelGen — DO NOT EDIT MANUALLY.
// Re-run scripts/ModelGen to regenerate from actos-backend/docs/openapi.json.

#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Actos.Models;

public sealed record AdminActionSummary(
    [property: System.Text.Json.Serialization.JsonPropertyName("action_type")] string ActionType,
    [property: System.Text.Json.Serialization.JsonPropertyName("admin_username")] string AdminUsername,
    [property: System.Text.Json.Serialization.JsonPropertyName("created_at")] string CreatedAt,
    [property: System.Text.Json.Serialization.JsonPropertyName("id")] string Id,
    [property: System.Text.Json.Serialization.JsonPropertyName("target_id")] long TargetId,
    [property: System.Text.Json.Serialization.JsonPropertyName("target_type")] string TargetType,
    [property: System.Text.Json.Serialization.JsonPropertyName("reason")] string? Reason = null
);
