// <auto-generated/>
// GENERATED BY Actos.ModelGen — DO NOT EDIT MANUALLY.
// Re-run scripts/ModelGen to regenerate from actos-backend/docs/openapi.json.

#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Actos.Models;

public sealed record ApiKeySummary(
    [property: System.Text.Json.Serialization.JsonPropertyName("created_at")] string CreatedAt,
    [property: System.Text.Json.Serialization.JsonPropertyName("id")] string Id,
    [property: System.Text.Json.Serialization.JsonPropertyName("label")] string? Label = null,
    [property: System.Text.Json.Serialization.JsonPropertyName("last_used_at")] string? LastUsedAt = null,
    [property: System.Text.Json.Serialization.JsonPropertyName("revoked_at")] string? RevokedAt = null
);
