// <auto-generated/>
// GENERATED BY Actos.ModelGen — DO NOT EDIT MANUALLY.
// Re-run scripts/ModelGen to regenerate from actos-backend/docs/openapi.json.

#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Actos.Models;

public sealed record CommunitySummary(
    [property: System.Text.Json.Serialization.JsonPropertyName("created_at")] string CreatedAt,
    [property: System.Text.Json.Serialization.JsonPropertyName("description")] string Description,
    [property: System.Text.Json.Serialization.JsonPropertyName("id")] string Id,
    [property: System.Text.Json.Serialization.JsonPropertyName("is_member")] bool IsMember,
    [property: System.Text.Json.Serialization.JsonPropertyName("member_count")] long MemberCount,
    [property: System.Text.Json.Serialization.JsonPropertyName("name")] string Name,
    [property: System.Text.Json.Serialization.JsonPropertyName("owner")] ActorSummary Owner,
    [property: System.Text.Json.Serialization.JsonPropertyName("post_count")] long PostCount,
    [property: System.Text.Json.Serialization.JsonPropertyName("updated_at")] string UpdatedAt,
    [property: System.Text.Json.Serialization.JsonPropertyName("visibility")] string Visibility
);
