// <auto-generated/>
// GENERATED BY Actos.ModelGen — DO NOT EDIT MANUALLY.
// Re-run scripts/ModelGen to regenerate from actos-backend/docs/openapi.json.

#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Actos.Models;

public sealed record ContentSummary(
    [property: System.Text.Json.Serialization.JsonPropertyName("author")] ActorSummary Author,
    [property: System.Text.Json.Serialization.JsonPropertyName("author_deleted")] bool AuthorDeleted,
    [property: System.Text.Json.Serialization.JsonPropertyName("body")] string Body,
    [property: System.Text.Json.Serialization.JsonPropertyName("body_format")] string BodyFormat,
    [property: System.Text.Json.Serialization.JsonPropertyName("comment_count")] int CommentCount,
    [property: System.Text.Json.Serialization.JsonPropertyName("content_type")] string ContentType,
    [property: System.Text.Json.Serialization.JsonPropertyName("created_at")] string CreatedAt,
    [property: System.Text.Json.Serialization.JsonPropertyName("deleted")] bool Deleted,
    [property: System.Text.Json.Serialization.JsonPropertyName("downvotes")] int Downvotes,
    [property: System.Text.Json.Serialization.JsonPropertyName("id")] string Id,
    [property: System.Text.Json.Serialization.JsonPropertyName("metadata")] JsonElement Metadata,
    [property: System.Text.Json.Serialization.JsonPropertyName("score")] int Score,
    [property: System.Text.Json.Serialization.JsonPropertyName("tags")] IReadOnlyList<string> Tags,
    [property: System.Text.Json.Serialization.JsonPropertyName("upvotes")] int Upvotes,
    [property: System.Text.Json.Serialization.JsonPropertyName("attachments")] IReadOnlyList<UploadResponse>? Attachments = null,
    [property: System.Text.Json.Serialization.JsonPropertyName("body_html")] string? BodyHtml = null,
    [property: System.Text.Json.Serialization.JsonPropertyName("edited_at")] string? EditedAt = null,
    [property: System.Text.Json.Serialization.JsonPropertyName("title")] string? Title = null
);
