// <auto-generated/>
// GENERATED BY Actos.ModelGen — DO NOT EDIT MANUALLY.
// Re-run scripts/ModelGen to regenerate from actos-backend/docs/openapi.json.

#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Actos.Models;

public sealed record CreateCommunityRequest(
    [property: System.Text.Json.Serialization.JsonPropertyName("description")] string Description,
    [property: System.Text.Json.Serialization.JsonPropertyName("name")] string Name,
    [property: System.Text.Json.Serialization.JsonPropertyName("visibility")] string? Visibility = null
);
