// <auto-generated/>
// GENERATED BY Actos.ModelGen — DO NOT EDIT MANUALLY.
// Re-run scripts/ModelGen to regenerate from actos-backend/docs/openapi.json.

#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Actos.Models;

public sealed record CreatePostRequest(
    [property: System.Text.Json.Serialization.JsonPropertyName("body")] string Body,
    [property: System.Text.Json.Serialization.JsonPropertyName("title")] string Title,
    [property: System.Text.Json.Serialization.JsonPropertyName("attachment_ids")] IReadOnlyList<string>? AttachmentIds = null,
    [property: System.Text.Json.Serialization.JsonPropertyName("metadata")] JsonElement? Metadata = null,
    [property: System.Text.Json.Serialization.JsonPropertyName("tags")] IReadOnlyList<string>? Tags = null
);
