// <auto-generated/>
// GENERATED BY Actos.ModelGen — DO NOT EDIT MANUALLY.
// Re-run scripts/ModelGen to regenerate from actos-backend/docs/openapi.json.

#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Actos.Models;

public sealed record CrossPostPreviewSummary(
    [property: System.Text.Json.Serialization.JsonPropertyName("author")] ActorSummary Author,
    [property: System.Text.Json.Serialization.JsonPropertyName("id")] string Id,
    [property: System.Text.Json.Serialization.JsonPropertyName("community")] CommunityRefSummary? Community = null,
    [property: System.Text.Json.Serialization.JsonPropertyName("title")] string? Title = null
);
