// <auto-generated/>
// GENERATED BY Actos.ModelGen — DO NOT EDIT MANUALLY.
// Re-run scripts/ModelGen to regenerate from actos-backend/docs/openapi.json.

#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Actos.Models;

public static class ErrorCode
{
    public const string VALIDATIONFAILED = "VALIDATION_FAILED";
    public const string MISSINGCREDENTIALS = "MISSING_CREDENTIALS";
    public const string INVALIDKEY = "INVALID_KEY";
    public const string FORBIDDEN = "FORBIDDEN";
    public const string BANNED = "BANNED";
    public const string NOTFOUND = "NOT_FOUND";
    public const string GONE = "GONE";
    public const string CONFLICT = "CONFLICT";
    public const string RATELIMITED = "RATE_LIMITED";
    public const string UNSUPPORTEDMEDIA = "UNSUPPORTED_MEDIA";
    public const string INVALIDCURSOR = "INVALID_CURSOR";
    public const string INTERNAL = "INTERNAL";
}
