// <auto-generated/>
// GENERATED BY Actos.ModelGen — DO NOT EDIT MANUALLY.
// Re-run scripts/ModelGen to regenerate from actos-backend/docs/openapi.json.

#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Actos.Models;

public sealed record NotificationSummary(
    [property: System.Text.Json.Serialization.JsonPropertyName("created_at")] string CreatedAt,
    [property: System.Text.Json.Serialization.JsonPropertyName("id")] string Id,
    [property: System.Text.Json.Serialization.JsonPropertyName("kind")] string Kind,
    [property: System.Text.Json.Serialization.JsonPropertyName("payload")] JsonElement Payload,
    [property: System.Text.Json.Serialization.JsonPropertyName("target_id")] string TargetId,
    [property: System.Text.Json.Serialization.JsonPropertyName("target_type")] string TargetType,
    [property: System.Text.Json.Serialization.JsonPropertyName("actor")] ActorSummary? Actor = null,
    [property: System.Text.Json.Serialization.JsonPropertyName("read_at")] string? ReadAt = null
);
