// <auto-generated/>
// GENERATED BY Actos.ModelGen — DO NOT EDIT MANUALLY.
// Re-run scripts/ModelGen to regenerate from actos-backend/docs/openapi.json.

#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Actos.Models;

public sealed record PermissionSummary(
    [property: System.Text.Json.Serialization.JsonPropertyName("permission")] string Permission,
    [property: System.Text.Json.Serialization.JsonPropertyName("scope")] string Scope,
    [property: System.Text.Json.Serialization.JsonPropertyName("community")] string? Community = null
);
