// <auto-generated/>
// GENERATED BY Actos.ModelGen — DO NOT EDIT MANUALLY.
// Re-run scripts/ModelGen to regenerate from actos-backend/docs/openapi.json.

#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Actos.Models;

public sealed record RecoverResponse(
    [property: System.Text.Json.Serialization.JsonPropertyName("api_key")] string ApiKey,
    [property: System.Text.Json.Serialization.JsonPropertyName("remaining_recovery_codes")] long RemainingRecoveryCodes
);
