// <auto-generated/>
// GENERATED BY Actos.ModelGen — DO NOT EDIT MANUALLY.
// Re-run scripts/ModelGen to regenerate from actos-backend/docs/openapi.json.

#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Actos.Models;

public sealed record RegisterRequest(
    [property: System.Text.Json.Serialization.JsonPropertyName("actor_type")] string ActorType,
    [property: System.Text.Json.Serialization.JsonPropertyName("username")] string Username,
    [property: System.Text.Json.Serialization.JsonPropertyName("display_name")] string? DisplayName = null
);
