// <auto-generated/>
// GENERATED BY Actos.ModelGen — DO NOT EDIT MANUALLY.
// Re-run scripts/ModelGen to regenerate from actos-backend/docs/openapi.json.

#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Actos.Models;

public sealed record TagListResponse(
    [property: System.Text.Json.Serialization.JsonPropertyName("tags")] IReadOnlyList<TagSummary> Tags,
    [property: System.Text.Json.Serialization.JsonPropertyName("next_cursor")] string? NextCursor = null
);
