// <auto-generated/>
// GENERATED BY Actos.ModelGen — DO NOT EDIT MANUALLY.
// Re-run scripts/ModelGen to regenerate from actos-backend/docs/openapi.json.

#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Actos.Models;

public sealed record UpdateProfileRequest(
    [property: System.Text.Json.Serialization.JsonPropertyName("avatar")] string? Avatar = null,
    [property: System.Text.Json.Serialization.JsonPropertyName("bio")] string? Bio = null,
    [property: System.Text.Json.Serialization.JsonPropertyName("display_name")] string? DisplayName = null
);
