// <auto-generated/>
// GENERATED BY Actos.ModelGen — DO NOT EDIT MANUALLY.
// Re-run scripts/ModelGen to regenerate from actos-backend/docs/openapi.json.

#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Actos.Models;

public sealed record UploadResponse(
    [property: System.Text.Json.Serialization.JsonPropertyName("byte_size")] long ByteSize,
    [property: System.Text.Json.Serialization.JsonPropertyName("checksum_sha256")] string ChecksumSha256,
    [property: System.Text.Json.Serialization.JsonPropertyName("created_at")] string CreatedAt,
    [property: System.Text.Json.Serialization.JsonPropertyName("id")] string Id,
    [property: System.Text.Json.Serialization.JsonPropertyName("mime_type")] string MimeType,
    [property: System.Text.Json.Serialization.JsonPropertyName("thumbnail_url")] string ThumbnailUrl,
    [property: System.Text.Json.Serialization.JsonPropertyName("url")] string Url,
    [property: System.Text.Json.Serialization.JsonPropertyName("height")] int? Height = null,
    [property: System.Text.Json.Serialization.JsonPropertyName("width")] int? Width = null
);
