// <auto-generated/>
// GENERATED BY Actos.ModelGen — DO NOT EDIT MANUALLY.
// Re-run scripts/ModelGen to regenerate from actos-backend/docs/openapi.json.

#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Actos.Models;

public sealed record Version(
    [property: System.Text.Json.Serialization.JsonPropertyName("api_version")] string ApiVersion,
    [property: System.Text.Json.Serialization.JsonPropertyName("git_sha")] string GitSha,
    [property: System.Text.Json.Serialization.JsonPropertyName("name")] string Name,
    [property: System.Text.Json.Serialization.JsonPropertyName("version")] string VersionValue
);
