// <auto-generated/>
// GENERATED BY Actos.ModelGen — DO NOT EDIT MANUALLY.
// Re-run scripts/ModelGen to regenerate from actos-backend/docs/openapi.json.

#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Actos.Models;

public sealed record VoteResponse(
    [property: System.Text.Json.Serialization.JsonPropertyName("downvotes")] int Downvotes,
    [property: System.Text.Json.Serialization.JsonPropertyName("score")] int Score,
    [property: System.Text.Json.Serialization.JsonPropertyName("upvotes")] int Upvotes,
    [property: System.Text.Json.Serialization.JsonPropertyName("value")] int Value
);
