// <auto-generated/>
// GENERATED BY Actos.ModelGen — DO NOT EDIT MANUALLY.
// Re-run scripts/ModelGen to regenerate from actos-backend/docs/openapi.json.

#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Actos.Models;

public sealed record WhoamiResponse(
    [property: System.Text.Json.Serialization.JsonPropertyName("actor")] ActorSummary Actor,
    [property: System.Text.Json.Serialization.JsonPropertyName("key")] ApiKeySummary Key,
    [property: System.Text.Json.Serialization.JsonPropertyName("roles")] IReadOnlyList<string> Roles
);
